on:
  push:
    branches:
      - main

env:
  REACT_APP_S3_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for React app
        run: |
          cd frontend
          npm install

      - name: Create .env file for React
        run: |
          cd frontend
          touch .env.local
          echo REACT_APP_S3_REGION="us-east-1" >> .env.local

      - name: Run build and tests for React app
        run: |
          cd frontend
          npm install
          npm install -g uuid
          npm run build

      - name: Install dependencies for linting React app
        run: |
          cd frontend
          npm install eslint eslint-plugin-react --save-dev

      - name: Lint the React app
        run: |
          cd frontend
          npx eslint src

      - name: Check linting status
        run: |
          cd frontend
          npx eslint src || exit 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Amplify
        run: |
          cd frontend
          npm install -g @aws-amplify/cli
          amplify configure --accessKeyId ${{ secrets.AWS_ACCESS_KEY_ID }} --secretAccessKey ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region us-east-1
          amplify init --yes
          amplify push --yes
